"""updated models

Revision ID: 39b5e6224992
Revises: e5f006686862
Create Date: 2026-03-22 05:13:11.045204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39b5e6224992'
down_revision = 'e5f006686862'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE TYPE referraltypeenum AS ENUM ('OPD', 'IPD')")
    op.execute("CREATE TYPE referralstatusenum AS ENUM ('pending', 'completed', 'cancelled')")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint('unique_doctor_slot', ['doctor_id', 'appointment_datetime'])
        batch_op.create_unique_constraint('unique_patient_slot', ['patient_id', 'appointment_datetime'])
        batch_op.create_foreign_key(None, 'specialization_dept', ['department_id'], ['id'])

    with op.batch_alter_table('doctor_availability', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint('unique_doctor_department_day', ['doctor_id', 'department_id', 'date'])
        batch_op.create_foreign_key(None, 'specialization_dept', ['department_id'], ['id'])

    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referral_type', sa.Enum('OPD', 'IPD', name='referraltypeenum'), nullable=False))
        batch_op.add_column(sa.Column('referral_status', sa.Enum('pending', 'completed', 'cancelled', name='referralstatusenum'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.drop_column('referral_status')
        batch_op.drop_column('referral_type')

    with op.batch_alter_table('doctor_availability', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('unique_doctor_department_day', type_='unique')
        batch_op.drop_column('department_id')

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('unique_patient_slot', type_='unique')
        batch_op.drop_constraint('unique_doctor_slot', type_='unique')
        batch_op.drop_column('department_id')

    # ### end Alembic commands ###
