"""add patient referral fields

Revision ID: 3b9b978b81e7
Revises: f9909878ff6c
Create Date: 2026-01-31 04:11:03.558756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b9b978b81e7'
down_revision = 'f9909878ff6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referred_by_doctor_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('referred_to_dept_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('referred_to_doctor_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('referral_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_referred', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(None, 'doctor', ['referred_to_doctor_id'], ['id'])
        batch_op.create_foreign_key(None, 'specialization_dept', ['referred_to_dept_id'], ['id'])
        batch_op.create_foreign_key(None, 'doctor', ['referred_by_doctor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('is_referred')
        batch_op.drop_column('referral_date')
        batch_op.drop_column('referred_to_doctor_id')
        batch_op.drop_column('referred_to_dept_id')
        batch_op.drop_column('referred_by_doctor_id')

    # ### end Alembic commands ###
