"""separate table for referrals

Revision ID: 53f704cf4673
Revises: 3b9b978b81e7
Create Date: 2026-02-06 04:49:21.884323

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '53f704cf4673'
down_revision = '3b9b978b81e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('referred_by_doctor_id', sa.Integer(), nullable=False),
    sa.Column('referred_to_dept_id', sa.Integer(), nullable=True),
    sa.Column('referred_to_doctor_id', sa.Integer(), nullable=False),
    sa.Column('referral_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.ForeignKeyConstraint(['referred_by_doctor_id'], ['doctor.id'], ),
    sa.ForeignKeyConstraint(['referred_to_dept_id'], ['specialization_dept.id'], ),
    sa.ForeignKeyConstraint(['referred_to_doctor_id'], ['doctor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('patient_referred_to_dept_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('patient_referred_to_doctor_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('patient_referred_by_doctor_id_fkey'), type_='foreignkey')
        batch_op.drop_column('referred_by_doctor_id')
        batch_op.drop_column('referred_to_doctor_id')
        batch_op.drop_column('referral_date')
        batch_op.drop_column('referred_to_dept_id')
        batch_op.drop_column('is_referred')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_referred', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('referred_to_dept_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('referral_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('referred_to_doctor_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('referred_by_doctor_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('patient_referred_by_doctor_id_fkey'), 'doctor', ['referred_by_doctor_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('patient_referred_to_doctor_id_fkey'), 'doctor', ['referred_to_doctor_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('patient_referred_to_dept_id_fkey'), 'specialization_dept', ['referred_to_dept_id'], ['id'])

    op.drop_table('referrals')
    # ### end Alembic commands ###
