"""update appointment datatetime fields and constriants

Revision ID: 94de8b41ac2b
Revises: 39b5e6224992
Create Date: 2026-08-11 15:52:19.365497

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '94de8b41ac2b'
down_revision = '39b5e6224992'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_datetime', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('end_datetime', sa.DateTime(), nullable=False))
        batch_op.drop_constraint(batch_op.f('unique_doctor_slot'), type_='unique')
        batch_op.drop_constraint(batch_op.f('unique_patient_slot'), type_='unique')
        batch_op.drop_column('appointment_datetime')

    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")

    op.execute("""
        ALTER TABLE appointment
        ADD CONSTRAINT exclude_patient_overlapping_appointment
        EXCLUDE USING gist (
            patient_id WITH =,
            tsrange(start_datetime, end_datetime, '[)') WITH &&
        )
        WHERE (status = 'booked')
    """)

    op.execute("""
        ALTER TABLE appointment
        ADD CONSTRAINT exclude_doctor_overlapping_appointment
        EXCLUDE USING gist (
            doctor_id WITH =,
            tsrange(start_datetime, end_datetime, '[)') WITH &&
        )
        WHERE (status = 'booked')
    """)

    op.execute("""
        ALTER TABLE doctor_availability
        ADD CONSTRAINT exclude_doctor_overlapping_availability
        EXCLUDE USING gist (
            doctor_id WITH =,
            tsrange(date + start_time, date + end_time, '[)') WITH &&
        )
    """)

    with op.batch_alter_table('doctor_availability', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('unique_doctor_department_day'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_availability', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('unique_doctor_department_day'), ['doctor_id', 'department_id', 'date'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appointment_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint(batch_op.f('unique_patient_slot'), ['patient_id', 'appointment_datetime'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('unique_doctor_slot'), ['doctor_id', 'appointment_datetime'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('end_datetime')
        batch_op.drop_column('start_datetime')

    # ### end Alembic commands ###
