"""make referral department mandatory and doctor nullable

Revision ID: e5f006686862
Revises: 53f704cf4673
Create Date: 2026-02-07 04:41:53.113723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5f006686862'
down_revision = '53f704cf4673'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.alter_column('referred_to_dept_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('referred_to_doctor_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.alter_column('referred_to_doctor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('referred_to_dept_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
